### ISSUE TITLE
no output when setting -t

### ISSUE THREAD

**Issue by evolgenomology** [DRL/kinfin#13]
Hey Dom,

a f*** piece of art, the whole thing I mean. Another issue though. Only defining IDX, PROTEOME, and OUT, but not giving a tree in the command I get results, e.g. the cluster_sizes.pdf. All good.
Using more labels like
File Edit Options Buffers Tools Text Help                                                                                               
`#IDX,PROTEOME,OUT,propagation,datatyp                                                                                                     0,ANAN,0,partheno,genome                                                                                                                1,ASU,1,sexual,genome                                                                                                                  2,BUX,0,sexual,genome                                                                                                                     3,CEL,1,herma,genome                                                                                                                      4,DF50,0,sexual,transctiptome                                                                                                           5,DL13,0,partheno,transcriptome                                                                                                         6,DL13G,0,partheno,transcriptome                                                                                                        7,ES5,0,sexual,genome                                                                                                                   8,JU76,0,herma,genome                                                                                                                   9,MFLO,0,partheno,genome                                                                                                                10,MHA,0,sexual,genome                                                                                                                  11,PDA,0,partheno,genome                                                                                                                12,PDAG,0,partheno,genome                                                                                                               13,PRED,0,sexual,genome                                                                                                                 14,PS11,0,partheno,genome                                                                                                               15,PS15,0,partheno,transcriptome                                                                                                        16,PS15G,0,partheno,genome                                                                                                              17,PSU,0,sexual,genome                                                                                                                  18,SRAE,1,sexual,genome`

and the full command including the -t, it stops at
```
...
[STATUS] - Writing /work/PanaGenomes/Pana_Ortho/Pana_OrthoFinder/test2.kinfin_results/tree/tree.node_metrics.txt ...
[STATUS] - Writing /work/PanaGenomes/Pana_Ortho/Pana_OrthoFinder/test2.kinfin_results/tree/tree.cluster_metrics.txt ...
[STATUS] - Writing tree /work/PanaGenomes/Pana_Ortho/Pana_OrthoFinder/test2.kinfin_results/tree/tree.pdf ...
ETE: cannot connect to X server```

but then the output only contains data in the *tree* subfolder. All other folders (datatype, global, ...) remain empty.

So I guess a continue on fail statement or something should do the trick.

Phil

**Comment by DRL** [comment]
Thanks! Great that you like it!

Yeah. Regarding that error. That is an issue with ETE3. Rendering within ETE3 is performed using a plotting library that gets unhappy when no X11 server is around. And that is obviously an issue on many headless machines. What happens is that the moment KinFin runs into this part of the code, ETE3 decides to quit the whole thing and no further files get written (that's why folders are empty, except the tree folder but which contains not ```tree.pdf``` file). See discussion [here](https://groups.google.com/forum/#!topic/etetoolkit/ePJlSFxQDIc)

There are two solutions:
1. Enable X11Forwarding in your ssh-config's
- You can try this, but if you use screen/tmux/qsub it will drive you insane as the initial X11 ```$DISPLAY``` becomes undetectable for ETE3 as you jump around. 

2. Get xvfb
- ```sudo apt-get install xvfb```
- Then running Kinfin using: ```xvfb-run ./kinfin.py ...```. 
- However, if you want to run multiple (parallel) KinFins at the same time, xvfb-run will complain. But you can use xvfb-run's ```-a``` option:  ```xvfb-run -a ./kinfin.py```

In upcoming versions of KinFin there will be an check for plotting issues at the beginning of the analysis.

Cheers, 

dom

**Comment by evolgenomology** [comment]
Thanks for the info!
Or, I just transfer it to my local machine/laptop for now… ;-)
I hate the X11 issues on my workstation (and esp. with tmux), I won’t even go into playing with this now.

But one other question. I just commented some lines in the SpeciesClassification.txt, because I thought I could just restrict to some species (there are two commented in your sample file). However, this leads to
``` File "./kinfin.py", line 1902, in <dictcomp>
    self.proteomes_by_protein_id = {protein_id : proteinCollection.proteinObjs_by_protein_id[protein_id].proteome_id for protein_id in
protein_ids}
KeyError: 'ANAN|g10010.t1’```

Cheers

Phil

On 21 Dec 2016, 23:27 +0000, Dominik R Laetsch <notifications@github.com>, wrote:
> Thanks! Great that you like it!
> Yeah. Regarding that error. That is an issue with ETE3. Rendering within ETE3 is performed using a plotting library that gets unhappy when no X11 server is around. And that is obviously an issue on many headless machines. What happens is that the moment KinFin runs into this part of the code, ETE3 decides to quit the whole thing and no further files get written (that's why folders are empty, except the tree folder but which contains not tree.pdf file). See discussion here
> There are two solutions:
>
> - Enable X11Forwarding in your ssh-config's
>
>
> - You can try this, but if you use screen/tmux/qsub it will drive you insane as the initial X11 $DISPLAY becomes undetectable for ETE3 as you jump around.
>
>
> - Get xvfb
>
>
> - sudo apt-get install xvfb
> - Then running Kinfin using: xvfb-run ./kinfin.py ....
> - However, if you want to run multiple (parallel) KinFins at the same time, xvfb-run will complain. But you can use xvfb-run's -a option: xvfb-run -a ./kinfin.py
>
> In upcoming versions of KinFin there will be an check for plotting issues at the beginning of the analysis.
> Cheers,
> dom
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by evolgenomology** [comment]
OK, because I am a curious mind and sleep is for Anfänger. The xvfb-run ./kinfin.py solution works. Thanks!

Cheers

Phil

**Comment by DRL** [comment]
Yes. That is not implemented yet. 

You'll have to simply delete the lines. 

Next release will have it.

**Comment by evolgenomology** [comment]
Hmmm, no, this doesn't work either. If I delete the relevant lines from the `SpeciesClassification.txt`file I get the same error as above.

**Comment by DRL** [comment]
Hi Phil, 

I think i fixed it now. Can you pull the latest version and see? 

Also can you put the command you executed, together with the issue? 

Should then be easier to follow for other people (not that anybody is reading this ... except Lewis)

cheers, 

dom

**Comment by evolgenomology** [comment]
Hi Dom,

will try at once. Here is the command for reference:
```xvfb-run ./kinfin.py  \
    -p /work/PanaGenomes/Pana_Ortho/Pana_OrthoFinder/SpeciesIDs.txt \
    -g /work/PanaGenomes/Pana_Ortho/Pana_OrthoFinder/Orthogroups.txt \
    -c /work/PanaGenomes/Pana_Ortho/Pana_OrthoFinder/SpeciesClassification.txt \
    -o /work/PanaGenomes/Pana_Ortho/Pana_OrthoFinder/Panakinfin \
    -s /work/PanaGenomes/Pana_Ortho/Pana_OrthoFinder/SequenceIDs.txt \
    -a /work/PanaGenomes/Pana_Ortho/Pana_OrthoFinder/ \
    -t /work/PanaGenomes/Pana_Ortho/Pana_OrthoFinder/orthoF2.nwk --nodesdb data/nodesDB.txt --taxranks genus```

**Comment by evolgenomology** [comment]
Hi Dom,

unfortunately
```xvfb-run ./kinfin.py  \
    -p /work/PanaGenomes/Pana_Ortho/Pana_OrthoFinder/SpeciesIDs.txt \
    -g /work/PanaGenomes/Pana_Ortho/Pana_OrthoFinder/Orthogroups.txt \
    -c /work/PanaGenomes/Pana_Ortho/Pana_OrthoFinder/SpeciesClassificationP.txt \
    -o /work/PanaGenomes/Pana_Ortho/Pana_OrthoFinder/Panakinfin2 \
    -s /work/PanaGenomes/Pana_Ortho/Pana_OrthoFinder/SequenceIDs.txt \
    -a /work/PanaGenomes/Pana_Ortho/Pana_OrthoFinder/ \
    -t /work/PanaGenomes/Pana_Ortho/Pana_OrthoFinder/orthoF2.nwk --nodesdb data/nodesDB.txt --taxranks genus```
with *SpeciesClassificationP.txt*
```#IDX,PROTEOME,OUT,taxid,propagation,datatype                                                                                                                                          4,DF50,0,55784,sexual,transctiptome                                                                                                                                                   5,DL13,0,55784,partheno,transcriptome                                                                                                                                                 6,DL13G,0,55784,partheno,transcriptome                                                                                                                                                7,ES5,0,55784,sexual,genome                                                                                                                                                           8,JU76,1,1510670,herma,genome                                                                                                                                                         11,PDA,0,55784,partheno,genome                                                                                                                                                        12,PDAG,0,55784,partheno,genome                                                                                                                                                       13,PRED,1,6232,sexual,genome                                                                                                                                                          14,PS11,0,55784,partheno,genome                                                                                                                                                       15,PS15,0,55784,partheno,transcriptome                                                                                                                                                16,PS15G,0,55784,partheno,genome                                                                                                                                                      17,PSU,0,55784,sexual,genome```

still fails with
```[STATUS] - Parsing /work/PanaGenomes/Pana_Ortho/Pana_OrthoFinder/Orthogroups.txt ... this may take a while
Traceback (most recent call last):
  File "./kinfin.py", line 2163, in <module>
    clusterCollection = dataFactory.build_ClusterCollection(inputObj)
  File "./kinfin.py", line 590, in build_ClusterCollection
    clusterObj = ClusterObj(cluster_id, protein_string)
  File "./kinfin.py", line 1903, in __init__
    self.proteomes_by_protein_id = {protein_id : proteinCollection.proteinObjs_by_protein_id[protein_id].proteome_id for protein_id in protein_ids}
  File "./kinfin.py", line 1903, in <dictcomp>
    self.proteomes_by_protein_id = {protein_id : proteinCollection.proteinObjs_by_protein_id[protein_id].proteome_id for protein_id in protein_ids}
KeyError: 'ANAN|g10010.t1'```

So basically, it is looking for the first proteins of species "0" in the original set.

Phil

**Comment by DRL** [comment]
Hi,

sorry, there was a misunderstanding. 

Exclusion of proteomes by commenting out only works on SequenceIDs, SpeciesIDs, functional annotation, ... not on Orthogroups.txt

Because I think just removing proteomes from orthogroups is not the correct way of doing it, since, if you had excluded the proteomes before clustering, the clusters would be different.
I think you should simply remove the "proteomes to exclude" from the BLAST files (the sequences to exclude will then have no blast hits), recluster, and then remove the singletons composed of sequences to exclude.

In order to do this:
1. Get sequenceIDs of sequences you want to exclude (check out [fgrep.pl](https://github.com/blaxterlab/scripts/blob/master/tools/fgrep.pl)
```fgrep.pl -d " " -f proteins_of_proteomes_to_exclude.txt SequenceIDs.txt > SequenceIDs.proteins_of_proteomes_to_exclude.txt```

2. Remove BLAST results using src/exclude_sequences_from_blast.py (I just added this in v0.7.9)
```parallel -j 64 'src/exclude_sequences_from_blast.py {} SequenceIDs.proteins_of_proteomes_to_exclude.txt Results_XXXYY/WorkingDirectory/new' ::: Results_XXXYY/WorkingDirectory/Blast*.txt```

3. Rename the ```Results_XXXYY/WorkingDirectory/new.Blast*.txt``` files (backup the original ones)

4. Recluster using orthofinder

5. Remove singleton proteins from orthogroups
```grep -v -w -Ff proteins_of_proteomes_to_exclude.txt Orthogroups.txt > Orthogroups.singletons_pruned.txt````

Sorry that this turned out to be more complicated.
